import React from "react";
import { PanFlip } from "../../animations/pan-animated";
import { color_scheme } from "../../constants";
const RecoverPassword = () => {
  return (
    <div className="w-100 wrapper d-flex align-items-center">
      <div className="w-100 px-2 px-md-0">
        <div className="col-md-4 col-sm-11 mx-auto card px-4 pb-4">
          <div className="my-3 w-100 d-flex justify-content-center">
            <PanFlip size={180} />
          </div>
          <h4 className="mb-3" style={{ color: color_scheme.primary }}>
            <strong> Momos - Recover password</strong>
          </h4>

          <form action="">
            <div className="form-group">
              <label htmlFor="">
                Enterm your email{" "}
                <small className="text-muted">
                  We will send an autogenerated password
                </small>
              </label>
              <input
                type="text"
                className="form-control"
                placeholder="Email address"
                required
                name="email"
              />
            </div>

            <div className="mt-3">
              <button className="btn btn-primary btn-block">
                <b>Recover password</b>
              </button>
            </div>
          </form>
          <br />
          <br className="d-none d-md-block" />
          <div>
            <label htmlFor="" className="">
              Want to signin?{" "}
              <a href="/auth/login" style={{ color: color_scheme.primary }}>
                Login
              </a>
            </label>
          </div>
        </div>
      </div>
    </div>
  );
};

export default RecoverPassword;
